baseURL = '/'
languageCode = 'en-us'
title = 'Blog'
theme = "hyde"
disqusShortname = "spf13"
googleAnalytics = "Your tracking code"

[params]
  themeColor = "theme-base-08"
  description = "Your custom description"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/username/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/username/"}
  ]
